services:
  bot:
    container_name: ts-bot
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
      - .env:/app/.env
