services:
  webapp:
    container_name: ts-webapp
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - .next/
            - .git/
        - action: rebuild
          path: package.json
