services:
  site:
    container_name: ts-site
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/.next
    ports:
      - "5000:5000"
    env_file: .env