services:
  webapp:
    container_name: ts-webapp
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
      - /app/.next
      - /app/node_modules
    ports:
      - "5000:5000"
